import Nav from "./components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./Provider";
import MobileNavButton from "./components/Mobilenav";
import QueryProvider from "./Queryprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"min-h-screen max-w-full bg-zinc-900 text-white"}>
        <AuthProvider>
          <QueryProvider>
            <Nav />
            {children}
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
