import Nav from "./components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./Provider";
import QueryProvider from "./Queryprovider";
import Footer from "./components/Footer";
import { Providers } from "./Themeprovider";
import { Separator } from "./components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"max-h-screen max-w-full bg-gray-100 dark:bg-zinc-950"}>
        <Providers>
          <AuthProvider>
            <QueryProvider>
              <Nav />
              <Separator />
              {children}
              <Footer />
            </QueryProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
